### ISSUE TITLE
`bin` vs `scripts`

### ISSUE THREAD

**Issue by hoelzer** [rki-mf1/PanAdapt#2]
What's the difference between these two folders? Can they be harmonized? 

I think in the nextflow world `bin` is more common to store cutom scripts that can then be directly used in the workflow.

**Comment by StefanFrankBio** [comment]
You are right, `scripts` is not necessary. It is legacy code, that I migrated to `bin` step by step. At this point all the relevant python script should have been added to `bin`. I will review it and then delete `scripts`.
