### ISSUE TITLE
Pipeline name

### ISSUE THREAD

**Issue by hoelzer** [rki-mf1/PanAdapt#3]
Any idea for a better name for the pipeline? : )

**Comment by StefanFrankBio** [comment]
What do you think about PANADAPT?

It shows Analysis of Positive Selection (Adaptation) as it's main focus and also mentions the pangenome approach. We are not mentioning bacteria or AMR, but I think that's fine, since possible usecases for this pipeline go beyond the my thesis focus.

**Comment by hoelzer** [comment]
Good idea, I like PANADAPT... it might sound a bit like "adaptation" happing in a pangenome. Which is not exactly what we're doing. But it's a good working name (better than UpDownSelect ;) )

**Comment by StefanFrankBio** [comment]
The reference to konami code is obviously lost on you! :)

Changed!

**Comment by hoelzer** [comment]
Yep, no clue what you are talking about :D
